name: cvideo_employer_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  # Built to be used with the bloc state management package.
  flutter_bloc: ^5.0.1
  # An abstract class that helps to implement equality without needing to explicitly override == and hashCode.
  equatable: ^1.2.0
  # This library contains the definitions of annotations that provide additional semantic information about the program being annotated.
  meta: ^1.1.8
  # Flutter plugin for Google Sign-In
  google_sign_in: ^4.5.1
  # Flutter plugin for Firebase Auth
  firebase_auth: ^0.16.1
  # Flutter plugin for Firebase Cloud Messaging.
  firebase_messaging: ^6.0.16
  # An SVG rendering and widget library for Flutter.
  flutter_svg: ^0.18.0
  # A composable, multi-platform, Future-based API for HTTP requests.
  http: ^0.12.1
  # A flutter plugin for bringing hex colors to dart hexcolorPlugin.
  hexcolor: ^1.0.2
  # Flutter Secure Storage provides API to store data in secure storage.
  flutter_secure_storage: ^3.3.3
  # Flutter plugin for displaying inline video with other Flutter widgets on Android and iOS.
  video_player: ^0.10.11+2
  # A light weight library to easily manage a progress dialog with simple steps whenever you need to do it. You can easily show and hide it.
  progress_dialog: ^1.2.4
  # Flutter plugin for reading and writing simple key-value pairs. Wraps NSUserDefaults on iOS and SharedPreferences on Android.
  shared_preferences: ^0.5.8
  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^4.3.1
  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.16.1
  # A package provides an easy way to add shimmer effect in Flutter project
  shimmer: ^1.1.1
  # A cross platform plugin for displaying and scheduling local notifications for Flutter applications with the ability to customise for each platform.
  flutter_local_notifications: ^1.4.4+2
  # A video player for Flutter with Cupertino and Material play controls
  chewie: ^0.9.10

  date_field: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/
    - assets/screens/common_icons/
    - assets/screens/scr001/
    - assets/screens/scr002/
    - assets/screens/scr003/
    - assets/screens/scr005/
    - assets/screens/scr004/
    - assets/screens/scr008/
    - assets/screens/scr010/

    - assets/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
